name: Clojure CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # It is important to install java before installing clojure tools which needs java
    # exclusions: babashka, clj-kondo and cljstyle
    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13
      with:
        lein: latest
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: lein deps
    - name: Build site
      run: lein cljsbuild once
    - name: Upload artifact
      id: deployment
      uses: actions/upload-pages-artifact@v5
      with:
        path: resources/public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
